language: node_js
node_js:
 - "stable"
cache:
  directories:
    - "node_modules"
services:
- postgresql
env:
- DB_USERNAME=chidinmaezekwe DB_PASSWORD=null DBNAME=art_cave_test
before_script:
- psql -c 'create database art_cave_test;' -U postgres
- psql -c "CREATE USER chidinmaezekwe WITH PASSWORD 'null';" -U postgres
script: npm test
after_success: npm run coverage
